// spec/fixtures/frontend/pages/Home.jsx
import React from 'react';
import { useTranslation } from 'react-i18next';

function Home() {
  const { t } = useTranslation();
  const welcomeMessage = t('common.hello');
  const currentStatus = 'done';

  return (
    <div>
      <h1>{welcomeMessage}</h1>
      <p>{t('common.goodbye')}</p>
      <span>{t(`status.${currentStatus}`)}</span>
    </div>
  );
}

export default Home;

// spec/fixtures/frontend/pages/Home.vue
<template>
  <div>
    <h1>{{ t('common.hello') }}</h1>
    <p>{{ t('common.goodbye') }}</p>
    <span>{{ t(`status.${currentStatus}`) }}</span>
  </div>
</template>

<script setup>
import { useI18n } from 'vue-i18n';

const { t } = useI18n();
const welcomeMessage = t('common.hello');
const currentStatus = 'done';
</script>
